import type { Organisation } from '@ug-gov/content-schemas';
import { pt } from './portableText';

export const organisations: Organisation[] = [
  {
    _id: 'org-state-house',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000001',
    title: 'State House',
    shortName: 'State House',
    slug: { current: 'state-house' },
    kind: 'state_house',
    mandate: 'Office and official residence of the President of the Republic of Uganda.',
    description: pt([
      'State House is the official residence and principal workplace of the President of Uganda, supporting the Head of State in performing constitutional, ceremonial and executive functions.',
    ]),
    website: 'https://www.statehouse.go.ug',
    featured: true,
  },
  {
    _id: 'org-opm',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000002',
    title: 'Office of the Prime Minister',
    shortName: 'OPM',
    slug: { current: 'office-of-the-prime-minister' },
    kind: 'ministry',
    mandate:
      'Leads, coordinates and supervises Government business in Cabinet, Parliament and Ministries, Departments and Agencies.',
    description: pt([
      'The Office of the Prime Minister (OPM) is responsible for the coordination and implementation of Government policies across Ministries, Departments and Agencies. The OPM also leads disaster preparedness and refugee management.',
    ]),
    website: 'https://www.opm.go.ug',
    featured: true,
  },
  {
    _id: 'org-moh',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000010',
    title: 'Ministry of Health',
    shortName: 'MoH',
    slug: { current: 'health' },
    kind: 'ministry',
    mandate:
      'To provide the highest possible level of health services to all people in Uganda through delivery of promotive, preventive, curative, palliative and rehabilitative health services.',
    description: pt([
      { h2: 'What we do' },
      'The Ministry of Health is responsible for policy formulation, resource mobilisation, quality assurance, capacity development and technical support across Uganda’s health sector. Through national referral hospitals, regional referral hospitals, district health systems and partnerships with the private-not-for-profit sector, the Ministry delivers care to Uganda’s population.',
      { h2: 'Our priorities' },
      {
        list: [
          'Strengthening primary health care and Village Health Teams',
          'Expanding universal health coverage',
          'Preventing and controlling communicable and non-communicable diseases',
          'Improving maternal, newborn, child and adolescent health',
          'Building the national health security and emergency response capability',
        ],
      },
    ]),
    contactEmail: 'info@health.go.ug',
    contactPhone: '+256 417 712 260',
    addressLines: ['Plot 6, Lourdel Road, Nakasero', 'P.O. Box 7272, Kampala'],
    website: 'https://www.health.go.ug',
    brandColor: '#0B6FB4',
    featured: true,
  },
  {
    _id: 'org-maaif',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000011',
    title: 'Ministry of Agriculture, Animal Industry and Fisheries',
    shortName: 'MAAIF',
    slug: { current: 'agriculture' },
    kind: 'ministry',
    mandate:
      'To transform subsistence agriculture into commercial agriculture that is competitive, profitable and sustainable.',
    description: pt([
      { h2: 'What we do' },
      'MAAIF formulates, reviews and implements agricultural policies, regulations and standards, and mobilises resources for agricultural development. The Ministry oversees crop, livestock and fisheries production; animal and plant health; extension services; and agribusiness development.',
      { h2: 'Our priorities' },
      {
        list: [
          'Single Spine Extension System rollout across all districts',
          'Pest, disease and vector control',
          'Strategic interventions in priority commodity value chains',
          'Irrigation development and climate-smart agriculture',
          'Support to cooperatives, SACCOs and farmer organisations',
        ],
      },
    ]),
    contactEmail: 'info@agriculture.go.ug',
    contactPhone: '+256 414 320 004',
    addressLines: ['Plot 16–18 Lugard Avenue, Entebbe', 'P.O. Box 102, Entebbe'],
    website: 'https://www.agriculture.go.ug',
    brandColor: '#2F7A3A',
    featured: true,
  },
  {
    _id: 'org-mofped',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000012',
    title: 'Ministry of Finance, Planning and Economic Development',
    shortName: 'MoFPED',
    slug: { current: 'finance' },
    kind: 'ministry',
    mandate:
      'To formulate sound economic policy and mobilise and manage resources for the socio-economic transformation of Uganda.',
    description: pt([
      { h2: 'What we do' },
      'MoFPED formulates fiscal and economic policy, prepares the national budget, manages public debt and public investment, and oversees development planning. The Ministry is the principal steward of public finances and the custodian of Uganda’s macroeconomic stability.',
      { h2: 'Our priorities' },
      {
        list: [
          'Prudent fiscal management and debt sustainability',
          'Implementation of the National Development Plan',
          'Domestic revenue mobilisation',
          'Financial inclusion through the Parish Development Model',
          'Public investment management',
        ],
      },
    ]),
    contactEmail: 'info@finance.go.ug',
    contactPhone: '+256 414 707 000',
    addressLines: ['Plot 2–8 Apollo Kaggwa Road', 'P.O. Box 8147, Kampala'],
    website: 'https://www.finance.go.ug',
    brandColor: '#1D4289',
    featured: true,
  },
  {
    _id: 'org-ura',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000020',
    title: 'Uganda Revenue Authority',
    shortName: 'URA',
    slug: { current: 'ura' },
    kind: 'authority',
    parent: { _ref: 'org-mofped' },
    mandate:
      'Assessment and collection of domestic taxes, customs duties and non-tax revenues on behalf of the Government of Uganda.',
    description: pt([
      'The Uganda Revenue Authority (URA) was established in 1991 as a central body to assess and collect specified tax revenue, administer and enforce the laws relating to such revenue, and to account for all the revenue to which those laws apply.',
    ]),
    website: 'https://www.ura.go.ug',
  },
  {
    _id: 'org-nira',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000021',
    title: 'National Identification and Registration Authority',
    shortName: 'NIRA',
    slug: { current: 'nira' },
    kind: 'authority',
    mandate:
      'Registers and issues National Identification Numbers and National Identity Cards to citizens; maintains the National Identification Register.',
    description: pt([
      'NIRA is responsible for the registration of persons and maintenance of the National Identification Register under the Registration of Persons Act, 2015.',
    ]),
    website: 'https://www.nira.go.ug',
  },
  {
    _id: 'org-ubos',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000022',
    title: 'Uganda Bureau of Statistics',
    shortName: 'UBOS',
    slug: { current: 'ubos' },
    kind: 'authority',
    mandate: 'The principal data-producing and coordinating agency of the National Statistical System.',
    website: 'https://www.ubos.org',
  },
  {
    _id: 'org-unra',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000023',
    title: 'Uganda National Roads Authority',
    shortName: 'UNRA',
    slug: { current: 'unra' },
    kind: 'authority',
    mandate: 'Develops and maintains the national roads network.',
    website: 'https://www.unra.go.ug',
  },
  {
    _id: 'org-ucc',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000024',
    title: 'Uganda Communications Commission',
    shortName: 'UCC',
    slug: { current: 'ucc' },
    kind: 'commission',
    mandate:
      'Regulates the communications sector — telecommunications, broadcasting, postal and data communications.',
    website: 'https://www.ucc.co.ug',
  },
  {
    _id: 'org-nita',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000025',
    title: 'National Information Technology Authority — Uganda',
    shortName: 'NITA-U',
    slug: { current: 'nita-u' },
    kind: 'authority',
    mandate:
      'Coordinates, promotes and monitors the development of information technology in Uganda for socio-economic development.',
    website: 'https://www.nita.go.ug',
    featured: false,
  },
  {
    _id: 'org-mia',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000013',
    title: 'Ministry of Internal Affairs',
    shortName: 'MIA',
    slug: { current: 'internal-affairs' },
    kind: 'ministry',
    mandate:
      'Responsible for immigration, citizenship, prisons, NGO registration, community service, and internal security coordination.',
    description: pt([
      'The Ministry of Internal Affairs oversees institutions that protect the internal security and rights of citizens — the Directorate of Citizenship and Immigration Control, Uganda Prisons Service, the NGO Bureau, and the Amnesty Commission.',
    ]),
    contactEmail: 'info@mia.go.ug',
    addressLines: ['Plot 75 Jinja Road', 'P.O. Box 7191, Kampala'],
    website: 'https://www.mia.go.ug',
    featured: false,
  },
  {
    _id: 'org-mtwa',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000014',
    title: 'Ministry of Tourism, Wildlife and Antiquities',
    shortName: 'MTWA',
    slug: { current: 'tourism' },
    kind: 'ministry',
    mandate:
      'Promotes tourism, conservation of wildlife and cultural heritage, and the development of the tourism sector.',
    description: pt([
      'MTWA formulates policy and coordinates the sector through partners including the Uganda Wildlife Authority (UWA), Uganda Tourism Board (UTB), Uganda Wildlife Education Centre (UWEC), and Uganda Wildlife Research and Training Institute.',
    ]),
    contactEmail: 'info@tourism.go.ug',
    addressLines: ['Plot 6 Kimathi Avenue', 'P.O. Box 4241, Kampala'],
    website: 'https://www.tourism.go.ug',
    featured: false,
  },
  {
    _id: 'org-mowt',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000015',
    title: 'Ministry of Works and Transport',
    shortName: 'MoWT',
    slug: { current: 'works-and-transport' },
    kind: 'ministry',
    mandate:
      'Develops and maintains national infrastructure — roads, railways, aviation and water transport — and regulates the transport sector.',
    description: pt([
      'The Ministry of Works and Transport oversees Uganda\'s physical infrastructure and transport systems, working with UNRA, Uganda Road Fund, UCAA, Uganda Railways Corporation and others.',
    ]),
    contactEmail: 'info@works.go.ug',
    addressLines: ['Old Port Bell Road', 'P.O. Box 7174, Kampala'],
    website: 'https://www.works.go.ug',
    featured: false,
  },
  {
    _id: 'org-mglsd',
    _type: 'organisation',
    contentId: '8e4a1e80-0001-4000-8000-000000000016',
    title: 'Ministry of Gender, Labour and Social Development',
    shortName: 'MGLSD',
    slug: { current: 'gender-labour-social-development' },
    kind: 'ministry',
    mandate:
      'Promotes gender equality, social protection, decent work and community development.',
    description: pt([
      'MGLSD coordinates social protection programmes including the Senior Citizens Grant (SAGE), the Youth Livelihood Programme and the Uganda Women Entrepreneurship Programme.',
    ]),
    contactEmail: 'info@mglsd.go.ug',
    addressLines: ['Plot 2 Simbamanyo House, George Street', 'P.O. Box 7136, Kampala'],
    website: 'https://www.mglsd.go.ug',
    featured: false,
  },
];
